from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

styles = getSampleStyleSheet()


def generate_pdf(name, subject, score, total, accuracy, grade, wrong_topics):

    filename = f"{name}_Quiz_Report.pdf"

    doc = SimpleDocTemplate(filename)

    story = []

    # ---------------- Title ----------------

    story.append(
        Paragraph(
            "<b>AI Learning Companion</b>",
            styles["Title"]
        )
    )

    story.append(
        Paragraph(
            "Quiz Performance Report",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 15))

    # ---------------- Date ----------------

    current_time = datetime.now().strftime("%d %b %Y  %I:%M %p")

    story.append(
        Paragraph(
            f"<b>Generated:</b> {current_time}",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 12))

    # ---------------- Summary Table ----------------

    table_data = [
        ["Student", name],
        ["Subject", subject],
        ["Score", f"{score}/{total}"],
        ["Accuracy", f"{accuracy:.2f}%"],
        ["Grade", grade],
    ]

    table = Table(table_data, colWidths=[120, 250])

    table.setStyle(
        TableStyle([
            ("GRID", (0, 0), (-1, -1), 1, colors.grey),
            ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
        ])
    )

    story.append(table)

    story.append(Spacer(1, 18))

    # ---------------- Topics ----------------

    story.append(
        Paragraph(
            "<b>Topics To Review</b>",
            styles["Heading2"]
        )
    )

    if wrong_topics:

        for topic in sorted(set(wrong_topics)):
            story.append(
                Paragraph(
                    f"• {topic}",
                    styles["Normal"]
                )
            )

    else:

        story.append(
            Paragraph(
                "Excellent! No weak topics found.",
                styles["Normal"]
            )
        )

    story.append(Spacer(1, 18))

    # ---------------- Feedback ----------------

    story.append(
        Paragraph(
            "<b>Performance Feedback</b>",
            styles["Heading2"]
        )
    )

    if grade == "A":
        feedback = (
            "Outstanding performance! Keep practicing to maintain "
            "your excellent understanding."
        )

    elif grade == "B":
        feedback = (
            "Good job! A little more practice will help you reach "
            "an excellent level."
        )

    elif grade == "C":
        feedback = (
            "Fair attempt. Spend more time revising the topics "
            "listed above."
        )

    else:
        feedback = (
            "Keep learning and practicing regularly. Consistent "
            "practice will improve your score."
        )

    story.append(
        Paragraph(
            feedback,
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 20))

    # ---------------- Footer ----------------

    story.append(
        Paragraph(
            "<hr/>",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            "<i>Generated by AI Learning Companion</i>",
            styles["Normal"]
        )
    )

    doc.build(story)

    return filename