from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch

styles = getSampleStyleSheet()
title_style = styles["Title"]
title_style.alignment = TA_CENTER

heading_style = styles["Heading2"]
heading_style.alignment = TA_CENTER

def generate_pdf(name, subject, score, total, accuracy, grade, wrong_topics):

    st = "NEW VERSION"
    print(st)

    filename = f"{name}_Quiz_Report.pdf"
    doc = SimpleDocTemplate(
    filename,
    rightMargin=40,
    leftMargin=40,
    topMargin=40,
    bottomMargin=40
)

    story = []

    # ---------------- Title ----------------

    story.append(
    Paragraph(
    "<font color='darkblue'><b>AI Learning Companion</b></font>",
    title_style
    )
)
    story.append(
    Paragraph(
        "<i>Personalized Quiz Performance Report</i>",
        styles["Italic"]
    )
)

    story.append(Spacer(1, 12))


    # ---------------- Date ----------------

    current_time = datetime.now().strftime("%d %b %Y | %I:%M %p")

    story.append(
    Paragraph(
        f"<b>Generated:</b> {current_time}",
        styles["Normal"]
    )
)

    story.append(Spacer(1, 0.2 * inch))

    # ---------------- Summary Table ----------------

    table_data = [
        ["Student", name],
        ["Subject", subject],
        ["Score", f"{score}/{total}"],
        ["Accuracy", f"{accuracy:.2f}%"],
        ["Grade", grade],
    ]

    table = Table(table_data, colWidths=[120, 250])

    table.setStyle(
    TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#E8F0FE")),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
        ("GRID", (0, 0), (-1, -1), 1, colors.grey),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ])
    )
    story.append(table)

    story.append(Spacer(1, 18))

    # ---------------- Topics ----------------

    story.append(
        Paragraph("<b>Topics To Review</b>", styles["Heading2"])
    )

    if wrong_topics:

        for topic in sorted(set(wrong_topics)):
            story.append(
                Paragraph(
                    f"• {topic}",
                    styles["Normal"]
                )
            )

    else:

        story.append(
            Paragraph(
                "Excellent! No weak topics found.",
                styles["Normal"]
            )
        )

    story.append(Spacer(1, 18))

    # ---------------- Feedback ----------------

    story.append(
    Paragraph("<b>Performance Feedback</b>", styles["Heading2"])
    )

    if grade == "A":
    
        feedback = (
    f"Excellent work, {name}! "
    "You demonstrated a strong understanding of the subject. "
    "Keep practicing to maintain your performance."
)

    elif grade == "B":
        feedback = (
            f"Excellent work, {name}! "
            "Good job! A little more practice will help you reach "
            "an excellent level."
        )

    elif grade == "C":
        feedback = (
        f"Fair attempt, {name}! "
        "Spend more time revising the topics "
        "listed above."
    )

    else:
        feedback = (
    f"Keep learning and practicing regularly, {name}. "
    "Consistent practice will improve your score."
)

    story.append(
        Paragraph(
            feedback,
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 20))

    # ---------------- Footer ----------------

    story.append(
        Paragraph(
            "<hr/>",
            styles["Normal"]
        )
    )

    
    story.append(
    Paragraph("<b>Keep Learning • Keep Growing</b>", heading_style)
)

    story.append(Spacer(1, 10))

    story.append(
    Paragraph(
        "<i>Generated by AI Learning Companion | Developed by Shiksha Saini | Version 1.0</i>",
        styles["Normal"]
    )
)
    

    doc.build(story)

    return filename